---

- name: Installing webserver(apache) & git
  ansible.builtin.apt:
    update_cache: true
    name: '{{ item }}'
    state: present
  loop:
    - apache2
    - git

- name: Enabling Apache2 required modules
  community.general.apache2_module:
    state: present
    name: '{{ item }}'
  loop:
    - rewrite
    - ssl
    - http2
    - headers
