---
- name: Install PHP
  ansible.builtin.apt:
    update_cache: true
    name: '{{ item }}'
    state: present
  loop:
    - php
    - php{{ php_version }}-curl
    - php{{ php_version }}-mbstring
    - php{{ php_version }}-xml
    - php{{ php_version }}-mysql
    - libapache2-mod-php
    - php{{ php_version }}-mysqli
  notify:
    - Restart apache
